[package]
name = "promtracker"
version = "0.6.0"
description = "Motoko value tracker for prometheus"
repository = "https://github.com/research-ag/promtracker"
keywords = [ "prometheus", "stats", "http", "metrics", "monitoring" ]
license = "Apache-2.0"

[dependencies]
base = "0.14.13"
new-base = "0.4.0"

[dev-dependencies]
motoko-matchers = "https://github.com/kritzcreek/motoko-matchers#v1.3.0@3dac8a071b69e4e651b25a7d9683fe831eb7cffd"

[requirements]
moc = "0.14.9"

[toolchain]
moc = "0.14.13"
